#!/usr/bin/env bash
# if Ubuntu container’s Nginx installation is not from listening on port 8?
#then configures nginx to run and listen to port 80

rm /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx restart
